### ISSUE TITLE
installation issue 1

### ISSUE THREAD

**Issue by Pratul13** [nic-crouch-sfc/pyconline-au-workshop-2020#1]
Error in command line installing:
conda install matplotlib scipy pandas -c conda-forge pip install ipython-sql

Error: unrecognised arguments: install ipython-sql

Screenshot of error is available at: https://drive.google.com/file/d/1lzbmI2poypWvGlq5NP9XtnueocQdPl-T/view?usp=sharing

**Comment by nic-crouch-sfc** [comment]
Ah - minor typo on my part. Apologies I couldn't see it during the session.
Should have been the following:
```
conda install matplotlib scipy pandas -c conda-forge 
pip install ipython-sql
```

Code is now correct in the readme. Thanks for the help!

**Comment by Pratul13** [comment]
Many thanks for such a prompt revert.

My personal opinion is that one learns only when there is a roadblock or some issue, else there is a propensity to take the easy way out aka Copy paste :)
