### ISSUE TITLE
Installation Issue 2

### ISSUE THREAD

**Issue by Pratul13** [nic-crouch-sfc/pyconline-au-workshop-2020#2]
Install encountered errors:
pip install fbprophet

There are 2 screenshots of the complete code execution including the errors:
https://drive.google.com/file/d/1eAOYNT7_VICGLqM4sfvkh3YJZVvD5gIB/view?usp=sharing
https://drive.google.com/file/d/1AvebyQJX3CrtD8JnSMQdlV11nMto3dHX/view?usp=sharing

**Comment by Pratul13** [comment]
The following code worked for me:
conda install -c conda-forge fbprophet

**Comment by nic-crouch-sfc** [comment]
Thanks for the tip @Pratul13 - will need to test once I get access to a Windows box; probably need to spin up a clean VM as I have build tools on all my physical ones.

**Comment by nic-crouch-sfc** [comment]
Went back to look at this in greater detail (very late on my part) but files no longer available.
